### ISSUE TITLE
Doesn't show the hit, and removes the xp drop

### ISSUE THREAD

**Issue by Wedel7** [geeckon/instant-damage-calculator#10]
Removes the xp drop for mage/range and doesn't show a hit, still gets the hp xp drop

**Comment by geeckon** [comment]
What activity were you doing when this was happening?

**Comment by Wedel7** [comment]
first i was doing corrupted gauntlet, then i tried to kick a man in lumbridge. Still same problem

**Comment by geeckon** [comment]
I don't use the plugin myself, so I downloaded it and tried it out.
At first I was having the same problem you described, but after changing some settings (unticking/ticking checkboxes), it started worked normally. I am not sure what the problem is, but at the moment I am probably not going to try to find and fix it, so try fiddling with the settings and if that doesn't work, maybe try reinstalling the plugin, maybe that helps.
