### ISSUE TITLE
Doesn't work in LMS

### ISSUE THREAD

**Issue by OilyHands** [geeckon/instant-damage-calculator#9]
It would be neat if it could work in LMS. For the time being, an option for the plugin to automatically disable in LMS would be neat. 

Instead of saying what number I was about to hit, it said a jargon of numbers, something with 5 or 6 digits (where it would usually say what I was about to hit). I think it was the same number every time, regardless of what I hit. I also think it said what number regardless if ths hit resulted in zero damage or not. 

A couple games later, I changed some settings and I ended up hitting a 1: https://imgur.com/a/Io8kCig

**Comment by geeckon** [comment]
The plugin stores the last hit it has calculated and when displaying a hit, it displays what it has stored. In LMS it is probably just displaying the last hit it stored before you entered there.

If I recall correctly, LMS has blocked xp drops, right? The plugin wasn't made to work with them but that is just because I was lazy. It would probably take just a few lines of code to make it work correctly.

**Comment by geeckon** [comment]
Probably the same problem as https://github.com/geeckon/instant-damage-calculator/issues/4

**Comment by geeckon** [comment]
This is because I calculate the hits based on xp gained and you get no experience in this minigame. Calculating them on the actual xp drops is not planned.
